sudo: false
language: java
jdk:
  - openjdk8

branches:
  only:
  - master
  - develop
  - release-*

before_install:
 - mvn clean

install:
  - mvn -DskipTests=true package

before_deploy:
  - mvn -DskipTests=true install
  - export ZIP_FILE=$(ls target/s3tos3util-*.zip)

deploy:
  provider: releases
  api_key: "${GITHUP_API_TOKEN}"
  file: "${ZIP_FILE}"
  skip_cleanup: true
  on:
    tags: true  
