sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11

branches:
  only:
  - master
  - develop
  - release-*

before_install:
 - mvn clean

after_success:
  - mvn clean install -dskipTests
